name: pr-build-pipeline

on:
  # Trigger analysis when pushing in main or pull requests, and when creating a pull request.
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  pr_build_pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install packages
        run: npm install

      - name: Check formatting
        run: npm run check-formatting

      - name: Build project and dependencies
        run: npm run build

      - name: Run unit tests and generate report
        run: npm run test:ci

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
